# Global build settings
[build]
   base    = ""        # run the build from this directory
   publish = "dist/"      # the output diretory to push to the CDN after the build
   command = "sed -i s/API_URL/$API_URL/g netlify.toml && npm run build"  # the command to build our site

# Redirects
[[redirects]]
  from = "/api/v1/*"
  to = "$API_URL/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200